/** Creating Order TYPES */
export const CREATE_ORDER_REQUEST = "CREATE_PROMO_CODE_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_PROMO_CODE_SUCCESS"
export const CREATE_ORDER_FAILED = "CREATE_PROMO_CODE_FAILED"

/** Get All Orders */
export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST"
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS"
export const GET_ALL_ORDERS_FAILED = "GET_ALL_ORDERS_FAILED"
